sudo: false
language: rust
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev # optional: only required for the --verify flag of coveralls
rust:
  - nightly
  - beta
  - stable
matrix:
  allow_failures:
    - rust: nightly
install:
- wget https://github.com/jedisct1/libsodium/releases/download/1.0.16/libsodium-1.0.16.tar.gz
- tar xvfz libsodium-1.0.16.tar.gz
- cd libsodium-1.0.16 && ./configure --prefix=$HOME/installed_libsodium && make && make install &&
  cd ..
- export PKG_CONFIG_PATH=$HOME/installed_libsodium/lib/pkgconfig:$PKG_CONFIG_PATH
- export LD_LIBRARY_PATH=$HOME/installed_libsodium/lib:$LD_LIBRARY_PATH
before_script:
  - |
      pip install --upgrade pip
      pip install 'travis-cargo' --user &&
      export PATH=$HOME/.local/bin:$PATH
script:
  - travis-cargo build
  - travis-cargo test
  - travis-cargo bench
after_success:
  - travis-cargo coveralls --no-sudo --verify
env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - secure: "..."
