sudo: false
language: rust
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev # optional: only required for the --verify flag of coveralls
rust:
  - nightly
  - beta
  - stable
matrix:
  allow_failures:
    - rust: nightly
before_script:
  - |
      pip install --upgrade pip
      pip install 'travis-cargo' --user &&
      export PATH=$HOME/.local/bin:$PATH
script:
  - travis-cargo build
  - travis-cargo test
  - travis-cargo bench
after_success:
  - travis-cargo coveralls --no-sudo --verify
env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - secure: "..."
