[package]
name = "modem"
version = "0.1.0"
authors = ["David Stainton <dstainton415@gmail.com>"]
description = "message oriented noise based cryptographic link layer for mixnets"
keywords = ["cryptography", "noise", "network", "mixnet"]

[dependencies]
snow = "0.1.12"
ecdh_wrapper = "0.0.1"
byteorder = "1.2.2"
subtle = "0.6.0"
sphinxcrypto = "0.0.5"

[dev-dependencies]
rustc-serialize = "0.3.24"
rand = "^0.4.2"