[package]
name = "modem"
version = "0.1.0"
authors = ["David Stainton <dstainton415@gmail.com>"]
description = "message oriented noise based cryptographic link layer"
keywords = ["cryptography", "noise", "network"]

[dependencies]
snow = { path = "../snow" }
#snow = "0.1.8-preview"
ecdh_wrapper = "0.0.0"
byteorder = "1.2.2"
subtle = "0.6.0"

[dev-dependencies]
ecdh_wrapper = "0.0.0"
rustc-serialize = "0.3.24"
mockstream = "0.0.3"